packages:
  - .

minimumReleaseAge: 1440

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

allowBuilds:
  '@firebase/util': true
  core-js: false
  protobufjs: true
  sharp: true
  unrs-resolver: true
